import { Plant } from "./plant";

export const PLANTS: Plant[] = [
  {
  id: 1,
  name: 'Astrantia',
  picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-for-garden-astrantia-1674846661.jpeg?crop=1xw:1xh;center,top&resize=980:*',
  bloom: 'Printemps à été',
  description: "Cette plante vivace moins connue est en fait un favori des jardins de cottage à l'ancienne. Ses jolies fleurs durent longtemps et attirent des tonnes de pollinisateurs.",
  created: new Date(),
  },
  {
  id: 2,
  name: 'Allium',
  picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-garden-flowers-purple-allium-1674847068.jpeg?crop=1xw:1xh;center,top&resize=980:*',
  bloom: 'A la fin du printemps',
  description: "De hautes fleurs en forme de globe (certaines sont aussi grosses que votre main!) Sont un ajout frappant au jardin printanier. Les rongeurs ne dérangeront pas ces bulbs.",
  created: new Date(),
  },
  {
    id: 3,
    name: 'Angelonia',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-for-garden-angelonia-1674847372.jpeg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: 'Printemps à Automne',
    description: "Les couleurs vives, les formes en cascade ou dressées et les fleurs qui fleurissent sans arrêt sont autant de raisons de planter cette annuelle dans vos plates-bandes, jardinières et pots. On l'appelle parfois muflier d'été.",
    created: new Date(),
  },
  {
    id: 4,
    name: 'Astrantia',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-for-garden-astrantia-1674846661.jpeg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: 'Printemps à été',
    description: "Cette plante vivace moins connue est en fait un favori des jardins de cottage à l'ancienne. Ses jolies fleurs durent longtemps et attirent des tonnes de pollinisateurs.",
    created: new Date(),
    },
    {
    id: 5,
    name: 'Allium',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-garden-flowers-purple-allium-1674847068.jpeg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: 'A la fin du printemps',
    description: "De hautes fleurs en forme de globe (certaines sont aussi grosses que votre main!) Sont un ajout frappant au jardin printanier. Les rongeurs ne dérangeront pas ces bulbs.",
    created: new Date(),
    },
    {
      id: 6,
      name: 'Angelonia',
      picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-for-garden-angelonia-1674847372.jpeg?crop=1xw:1xh;center,top&resize=980:*',
      bloom: 'Printemps à Automne',
      description: "Les couleurs vives, les formes en cascade ou dressées et les fleurs qui fleurissent sans arrêt sont autant de raisons de planter cette annuelle dans vos plates-bandes, jardinières et pots. On l'appelle parfois muflier d'été.",
      created: new Date(),
    },
    {
    id: 7,
    name: 'Astrantia',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-for-garden-astrantia-1674846661.jpeg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: 'Printemps à été',
    description: "Cette plante vivace moins connue est en fait un favori des jardins de cottage à l'ancienne. Ses jolies fleurs durent longtemps et attirent des tonnes de pollinisateurs.",
    created: new Date(),
    },
    {
    id: 8,
    name: 'Allium',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-garden-flowers-purple-allium-1674847068.jpeg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: 'A la fin du printemps',
    description: "De hautes fleurs en forme de globe (certaines sont aussi grosses que votre main!) Sont un ajout frappant au jardin printanier. Les rongeurs ne dérangeront pas ces bulbs.",
    created: new Date(),
    },
    {
      id: 9,
      name: 'Angelonia',
      picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-for-garden-angelonia-1674847372.jpeg?crop=1xw:1xh;center,top&resize=980:*',
      bloom: 'Printemps à Automne',
      description: "Les couleurs vives, les formes en cascade ou dressées et les fleurs qui fleurissent sans arrêt sont autant de raisons de planter cette annuelle dans vos plates-bandes, jardinières et pots. On l'appelle parfois muflier d'été.",
      created: new Date(),
    }
  ]
