import { Plant } from "./plant";

export const PLANTS: Plant[] = [
  {
  id: 1,
  name: 'Astrantia',
  picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-for-garden-astrantia-1674846661.jpeg?crop=1xw:1xh;center,top&resize=980:*',
  bloom: 'Printemps à été',
  description: "Cette plante vivace moins connue est en fait un favori des jardins de cottage à l'ancienne. Ses jolies fleurs durent longtemps et attirent des tonnes de pollinisateurs.",
  created: new Date(),
  },
  {
  id: 2,
  name: 'Allium',
  picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-garden-flowers-purple-allium-1674847068.jpeg?crop=1xw:1xh;center,top&resize=980:*',
  bloom: 'A la fin du printemps',
  description: "De hautes fleurs en forme de globe (certaines sont aussi grosses que votre main!) Sont un ajout frappant au jardin printanier. Les rongeurs ne dérangeront pas ces bulbs.",
  created: new Date(),
  },
  {
    id: 3,
    name: 'Angelonia',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-for-garden-angelonia-1674847372.jpeg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: 'Printemps à Automne',
    description: "Les couleurs vives, les formes en cascade ou dressées et les fleurs qui fleurissent sans arrêt sont autant de raisons de planter cette annuelle dans vos plates-bandes, jardinières et pots. On l'appelle parfois muflier d'été.",
    created: new Date(),
  },
  {
    id: 4,
    name: 'Aster',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/aster-types-of-flowers-1579719549.jpg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: "Milieu de l'Eté à Automne",
    description: "C'est l'une de nos vivaces préférées pour une raison ! L'aster fleurit pendant une longue période, ajoutant de la couleur au moment où toutes les autres fleurs se terminent pour la saison.",
    created: new Date(),
    },
    {
    id: 5,
    name: 'Calendula',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/types-of-flowers-calendula-1674848889.jpeg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: "Du Printemps au milieu de l'Eté",
    description: "Ces favoris à l'ancienne sont faciles à cultiver à partir de graines, et leurs pétales orange vif ou jaune font un magnifique contraste avec les fleurs bleues ou violettes.",
    created: new Date(),
    },
    {
      id: 6,
      name: 'Chrysanthemums',
      picture: 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-1184794974-612x612-1612205319.jpg?crop=0.8888888888888888xw:1xh;center,top&resize=980:*',
      bloom: 'Eté à Automne',
      description: "Les couleurs vives. Plantez ces plantes vivaces au printemps pour que leurs racines puissent s'établir et survivre à l'hiver. ",
      created: new Date(),
    },
    {
    id: 7,
    name: 'Columbine',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-934782262-612x612-1612205536.jpg?crop=1xw:1xh;center,top&resize=980:*',
    bloom: 'Printemps',
    description: "Les fleurs délicates sont si exotiques, mais ces plantes vivaces sont résistantes et très résistantes au froid. Plantez-les avec d'autres plantes vivaces et annuelles de printemps pour un meilleur effet. On les appelle aussi parfois le bonnet de grand-mère (comme c'est mignon !).",
    created: new Date(),
    },
    {
    id: 8,
    name: 'Crocus',
    picture: 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-128138404-612x612-1612205731.jpg?crop=1xw:0.9950980392156863xh;center,top&resize=980:*',
    bloom: 'Printemps',
    description: "Ces petites fleurs apparaissent au début du printemps, souvent lorsqu'il y a encore de la neige au sol. Plantez à l'automne pour une floraison printanière qui revient année après année.",
    created: new Date(),
    },
    {
      id: 9,
      name: 'Daffodil',
      picture: 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-128133356-612x612-1612205822.jpg?crop=1xw:1xh;center,top&resize=980:*',
      bloom: 'Début du Printemps',
      description: "Leurs têtes branlantes sont l'un des premiers signes du printemps - de plus, les rongeurs ne dérangeront pas ces bulbes (contrairement aux tulipes et aux crocus). Plantez à l'automne pour des fleurs printanières, qui devraient revenir pendant de nombreuses années.",
      created: new Date(),
    }
  ]
